### ISSUE TITLE
1.x branch?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/discipline-munit#175]
A 2.x series was just opened.  There are a bunch of bumps on 1.x that have been overlooked.  None of them appear to be anything that's critical to end users.

We could fork off a series/1.x, but I don't see any reason to actively maintain it with 2.x coming.  I anyone has the energy to give 1.x a sendoff, that's the way to do it, but I'm not volunteering.

**Comment by armanbilge** [comment]
No requests for a 1.x release in over a year, I think we're good.
