### ISSUE TITLE
Request release to support Scala Native 0.5.0

### ISSUE THREAD

**Issue by ekrich** [typelevel/discipline-munit#294]
I believe this is s blocker for Cats https://github.com/typelevel/cats/issues/4587.

Thanks, this would free up a bunch of downstream once Cats is ready.

**Comment by satorg** [comment]
The current version is 2.0.0-M3.
But since MUnit went 1.0.0-RC1, does it make sense for discipline-munit to release its RC1 too?

**Comment by ekrich** [comment]
Makes sense to me but I am not sure about the versioning scheme.

**Comment by TonioGela** [comment]
> Makes sense to me but I am not sure about the versioning scheme.

There's support in sbt-tl for RC versions: https://typelevel.org/sbt-typelevel/faq.html

**Comment by djspiewak** [comment]
With respect to semver, the constraint I tend to follow is that you shouldn't imply a degree of version stability which is *stricter* than what your upstream provides. So if the upstream is on an RC, you shouldn't release an untagged version. However, if your upstream is an RC, there's no reason you shouldn't be allowed to release an M. So in other words, I'm aligned with your plan!

**Comment by TonioGela** [comment]
Here's the release: https://github.com/typelevel/discipline-munit/releases/tag/v2.0.0-M4
